"""stage store tables

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 12:47:23.001231
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rationale_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(length=2), nullable=False),
    sa.Column('rationale_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'stage', 'rationale_id')
    )
    with op.batch_alter_table('rationale_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rationale_reviews_assessment_id'), ['assessment_id'], unique=False)

    op.create_table('stage_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(length=2), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('based_on_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('refused_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['based_on_run_id'], ['stage_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'stage', 'run_number')
    )
    with op.batch_alter_table('stage_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stage_runs_assessment_id'), ['assessment_id'], unique=False)

    op.create_table('assumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('assumption_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['stage_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'assumption_id')
    )
    with op.batch_alter_table('assumptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assumptions_run_id'), ['run_id'], unique=False)

    op.create_table('conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('conflict_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('proposed_resolution', sa.Text(), nullable=False),
    sa.Column('auto_resolved', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['stage_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'conflict_id')
    )
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conflicts_run_id'), ['run_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('client_doc_ref', sa.String(), nullable=True),
    sa.Column('date_on_document', sa.String(length=10), nullable=True),
    sa.Column('date_received', sa.String(length=10), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('read_status', sa.String(), nullable=False),
    sa.Column('read_status_reason', sa.Text(), nullable=True),
    sa.Column('reading_method', sa.String(), nullable=False),
    sa.Column('page_methods', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('unread_parts', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('reader_version', sa.String(), nullable=True),
    sa.Column('precedence_rank', sa.Integer(), nullable=False),
    sa.Column('used_for', sa.Text(), nullable=False),
    sa.Column('ignored_and_why', sa.Text(), nullable=False),
    sa.Column('doc_type_label', sa.String(), nullable=True),
    sa.Column('rank_override_decision_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['stage_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'doc_id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_run_id'), ['run_id'], unique=False)

    op.create_table('facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('fact_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('fact_type', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('fact_group', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['stage_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'fact_id')
    )
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facts_run_id'), ['run_id'], unique=False)

    op.create_table('functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('function_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('endpoints', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('data_read', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('data_written', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('privileged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['stage_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'function_id')
    )
    with op.batch_alter_table('functions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_functions_run_id'), ['run_id'], unique=False)

    op.create_table('item_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('boundary_text', sa.Text(), nullable=False),
    sa.Column('boundary_proposed', sa.Boolean(), nullable=False),
    sa.Column('stakeholders', sa.JSON(none_as_null=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['stage_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['stage_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'zone_id')
    )
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zones_run_id'), ['run_id'], unique=False)

    op.create_table('conflict_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conflict_pk', sa.Integer(), nullable=False),
    sa.Column('fact_pk', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conflict_pk'], ['conflicts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fact_pk'], ['facts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conflict_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conflict_facts_conflict_pk'), ['conflict_pk'], unique=False)

    op.create_table('containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_pk', sa.Integer(), nullable=True),
    sa.Column('zone_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_pk'], ['containers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['stage_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_pk'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'container_id')
    )
    with op.batch_alter_table('containers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_containers_run_id'), ['run_id'], unique=False)

    op.create_table('fact_refs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('owner_kind', sa.String(), nullable=False),
    sa.Column('owner_pk', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('fact_pk', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fact_pk'], ['facts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['stage_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fact_refs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fact_refs_run_id'), ['run_id'], unique=False)

    op.create_table('fact_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fact_pk', sa.Integer(), nullable=False),
    sa.Column('document_pk', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('quote', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['document_pk'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fact_pk'], ['facts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fact_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fact_sources_fact_pk'), ['fact_pk'], unique=False)

    op.create_table('elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('kind_label', sa.String(), nullable=True),
    sa.Column('parent_container_pk', sa.Integer(), nullable=True),
    sa.Column('zone_pk', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('hosting_type', sa.String(), nullable=True),
    sa.Column('internet_exposed', sa.String(), nullable=True),
    sa.Column('is_entry_point', sa.Boolean(), nullable=False),
    sa.Column('auth_method', sa.String(), nullable=True),
    sa.Column('owner_operator', sa.String(), nullable=False),
    sa.Column('data_handled', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('stated_security_config', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parent_container_pk'], ['containers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['stage_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_pk'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'element_id')
    )
    with op.batch_alter_table('elements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_elements_run_id'), ['run_id'], unique=False)

    op.create_table('function_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('function_pk', sa.Integer(), nullable=False),
    sa.Column('element_pk', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['element_pk'], ['elements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['function_pk'], ['functions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('function_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_function_members_function_pk'), ['function_pk'], unique=False)

    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.String(), nullable=False),
    sa.Column('link_type', sa.String(), nullable=False),
    sa.Column('source_pk', sa.Integer(), nullable=False),
    sa.Column('destination_pk', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('port', sa.String(), nullable=True),
    sa.Column('usage_at_destination', sa.Text(), nullable=False),
    sa.Column('authentication', sa.Text(), nullable=False),
    sa.Column('encryption', sa.Text(), nullable=False),
    sa.Column('data_carried', sa.JSON(none_as_null=True), nullable=False),
    sa.Column('crosses_trust_boundary', sa.Boolean(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('sync_async', sa.String(), nullable=True),
    sa.Column('rate_limiting', sa.String(), nullable=True),
    sa.Column('volume', sa.String(), nullable=True),
    sa.Column('inferred_from_text', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['destination_pk'], ['elements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['stage_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_pk'], ['elements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'link_id')
    )
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_links_run_id'), ['run_id'], unique=False)

    op.create_table('responsibility_splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('element_pk', sa.Integer(), nullable=False),
    sa.Column('provider_side', sa.Text(), nullable=False),
    sa.Column('customer_side', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['element_pk'], ['elements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['stage_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('responsibility_splits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_responsibility_splits_run_id'), ['run_id'], unique=False)

    op.create_table('scope_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('element_pk', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('assumed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['element_pk'], ['elements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['stage_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'decision_id'),
    sa.UniqueConstraint('run_id', 'element_pk')
    )
    with op.batch_alter_table('scope_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scope_decisions_run_id'), ['run_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('target_element_pk', sa.Integer(), nullable=True),
    sa.Column('target_link_pk', sa.Integer(), nullable=True),
    sa.Column('target_container_pk', sa.Integer(), nullable=True),
    sa.Column('fact_type', sa.String(), nullable=False),
    sa.Column('topic', sa.String(length=80), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('default_if_unanswered', sa.Text(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answered_by', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['stage_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_container_pk'], ['containers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_element_pk'], ['elements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_link_pk'], ['links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'question_id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_run_id'), ['run_id'], unique=False)

    op.create_table('assumption_basis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assumption_pk', sa.Integer(), nullable=False),
    sa.Column('fact_pk', sa.Integer(), nullable=True),
    sa.Column('question_pk', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assumption_pk'], ['assumptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fact_pk'], ['facts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_pk'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assumption_basis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assumption_basis_assumption_pk'), ['assumption_pk'], unique=False)

    op.create_table('rationale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('rationale_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(length=2), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('attention', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('concluded', sa.Text(), nullable=False),
    sa.Column('why_note', sa.Text(), nullable=True),
    sa.Column('assumed', sa.Text(), nullable=False),
    sa.Column('would_change', sa.Text(), nullable=False),
    sa.Column('question_pk', sa.Integer(), nullable=True),
    sa.Column('conflict_pk', sa.Integer(), nullable=True),
    sa.Column('auto_resolved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['conflict_pk'], ['conflicts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_pk'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['stage_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'rationale_id')
    )
    with op.batch_alter_table('rationale_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rationale_items_run_id'), ['run_id'], unique=False)

    op.create_table('scope_decision_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_pk', sa.Integer(), nullable=False),
    sa.Column('question_pk', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['decision_pk'], ['scope_decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_pk'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scope_decision_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scope_decision_questions_decision_pk'), ['decision_pk'], unique=False)

    op.create_table('rationale_affects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rationale_pk', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rationale_pk'], ['rationale_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rationale_affects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rationale_affects_rationale_pk'), ['rationale_pk'], unique=False)

    op.create_table('rationale_based_on',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rationale_pk', sa.Integer(), nullable=False),
    sa.Column('based_on_pk', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['based_on_pk'], ['rationale_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rationale_pk'], ['rationale_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rationale_based_on', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rationale_based_on_rationale_pk'), ['rationale_pk'], unique=False)

    op.create_table('rationale_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rationale_pk', sa.Integer(), nullable=False),
    sa.Column('document_pk', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('quote', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['document_pk'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rationale_pk'], ['rationale_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rationale_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rationale_sources_rationale_pk'), ['rationale_pk'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rationale_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rationale_sources_rationale_pk'))

    op.drop_table('rationale_sources')
    with op.batch_alter_table('rationale_based_on', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rationale_based_on_rationale_pk'))

    op.drop_table('rationale_based_on')
    with op.batch_alter_table('rationale_affects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rationale_affects_rationale_pk'))

    op.drop_table('rationale_affects')
    with op.batch_alter_table('scope_decision_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scope_decision_questions_decision_pk'))

    op.drop_table('scope_decision_questions')
    with op.batch_alter_table('rationale_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rationale_items_run_id'))

    op.drop_table('rationale_items')
    with op.batch_alter_table('assumption_basis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assumption_basis_assumption_pk'))

    op.drop_table('assumption_basis')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_run_id'))

    op.drop_table('questions')
    with op.batch_alter_table('scope_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scope_decisions_run_id'))

    op.drop_table('scope_decisions')
    with op.batch_alter_table('responsibility_splits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_responsibility_splits_run_id'))

    op.drop_table('responsibility_splits')
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_links_run_id'))

    op.drop_table('links')
    with op.batch_alter_table('function_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_function_members_function_pk'))

    op.drop_table('function_members')
    with op.batch_alter_table('elements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_elements_run_id'))

    op.drop_table('elements')
    with op.batch_alter_table('fact_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_sources_fact_pk'))

    op.drop_table('fact_sources')
    with op.batch_alter_table('fact_refs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_refs_run_id'))

    op.drop_table('fact_refs')
    with op.batch_alter_table('containers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_containers_run_id'))

    op.drop_table('containers')
    with op.batch_alter_table('conflict_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conflict_facts_conflict_pk'))

    op.drop_table('conflict_facts')
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zones_run_id'))

    op.drop_table('zones')
    op.drop_table('item_definitions')
    with op.batch_alter_table('functions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_functions_run_id'))

    op.drop_table('functions')
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facts_run_id'))

    op.drop_table('facts')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_run_id'))

    op.drop_table('documents')
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conflicts_run_id'))

    op.drop_table('conflicts')
    with op.batch_alter_table('assumptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assumptions_run_id'))

    op.drop_table('assumptions')
    with op.batch_alter_table('stage_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stage_runs_assessment_id'))

    op.drop_table('stage_runs')
    with op.batch_alter_table('rationale_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rationale_reviews_assessment_id'))

    op.drop_table('rationale_reviews')
    # ### end Alembic commands ###
