"""stage jobs

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-03 11:36:31.166556
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stage_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('run_number', sa.Integer(), nullable=True),
    sa.Column('refused_count', sa.Integer(), nullable=True),
    sa.Column('output_dir', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'stage')
    )
    with op.batch_alter_table('stage_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stage_jobs_assessment_id'), ['assessment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stage_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stage_jobs_assessment_id'))

    op.drop_table('stage_jobs')
    # ### end Alembic commands ###
